#!/bin/bash

#Define colors
normal=$(echo -en "\e[0m")
orange=$(echo -en "\e[33m")
aqua=$(echo -en "\e[36m")
lightgreen=$(echo -en "\e[92m")

rm harry >/dev/null 2>&1
rm /usr/local/bin/harry >/dev/null 2>&1
curl https://raw.githubusercontent.com/harryraj/global_index_source/master/harry >harry 2>/dev/null
mv harry /usr/local/bin
chmod +x /usr/local/bin/harry

if ! command -v harry &>/dev/null; then
    echo "${orange}Installation Failed !!!"
    echo "Posssible Solution : Run as root or check non-root version.${normal}"
    exit
else
    harry
fi
